version: "1"

volumes:
  postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/dockerfile
    image: newsletter_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
      - /app/.env # do not link this directory
      - /app/newsletter_spa  # do not link this directory
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: "postgres:12.3"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: newsletter_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: newsletter_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: newsletter_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
