# Generated by Django 4.1.3 on 2022-11-15 23:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='READY', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.FileField(upload_to='newsletters/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='newsletteritem',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='newsletters.newsletter'),
        ),
    ]
