# Generated by Django 4.1.3 on 2022-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_newsletter_status_alter_newsletter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='scheduled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
