# Generated by Django 4.1.3 on 2022-11-16 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_newsletter_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='unsubscribe_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='topicsusbscription',
            name='unsubscribe_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
