# Generated by Django 4.1.3 on 2022-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_alter_recipient_unsubscribe_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
